name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          GITHUB_TOKEN: ${{ secrets.T_key }}
          DEPLOY_KEY_PUBLIC: ${{ variables.D_key }}
        run: |
          terraform plan \
            -var="github_token=$GITHUB_TOKEN" \
            -var="github_owner=NagiosT" \
            -var="repository_name=github-terraform-task-NagiosT" \
            -var="deploy_key_public=$DEPLOY_KEY_PUBLIC"
